import {
  COMPASS_KIT_GENERATED_DIR,
  TRACK_TS_PATH,
} from "@scripts/desktop-export/paths";
import {
  snakeToCamelCase,
  swiftEnumCaseName,
} from "@scripts/desktop-export/swift-identifiers";
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const PRODUCT_EVENT_SWIFT_PATH = join(
  COMPASS_KIT_GENERATED_DIR,
  "ProductEvent.swift",
);

export const parseProductEventNames = (trackSource: string): string[] => {
  const typeStart = trackSource.indexOf("export type ProductEvent =");
  if (typeStart === -1) {
    throw new Error("ProductEvent union not found in track.ts");
  }
  const unionBodyStart = trackSource.indexOf("|", typeStart);
  const unionBodyEnd = trackSource.indexOf(
    "export type ProductEventProperties",
  );
  if (unionBodyStart === -1 || unionBodyEnd === -1) {
    throw new Error("ProductEvent union boundaries not found in track.ts");
  }
  const unionBody = trackSource.slice(unionBodyStart, unionBodyEnd);
  const events = [...unionBody.matchAll(/\|\s*"([^"]+)"/g)].map(
    (match) => match[1] as string,
  );
  if (events.length === 0) {
    throw new Error("ProductEvent union parsed zero events");
  }
  return events;
};

export const emitProductEventSwift = (
  trackSource = readFileSync(TRACK_TS_PATH, "utf8"),
): string => {
  const events = parseProductEventNames(trackSource);
  const cases = events
    .map((event) => {
      const swiftCase = swiftEnumCaseName(snakeToCamelCase(event));
      return `    case ${swiftCase} = "${event}"`;
    })
    .join("\n");

  return `// Generated by bun cli desktop:export. Do not edit.

import Foundation

public enum ProductEvent: String, Codable, Hashable, Sendable, CaseIterable {
${cases}
}
`;
};
