import {
  COMPASS_KIT_GENERATED_DIR,
  TRACK_TS_PATH,
} from "@scripts/desktop-export/paths";
import {
  snakeToCamelCase,
  swiftEnumCaseName,
} from "@scripts/desktop-export/swift-identifiers";
import { NATIVE_PRODUCT_EVENT_CALL_SITES } from "@core/desktop/native-product-events.manifest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const PRODUCT_EVENT_SWIFT_PATH = join(
  COMPASS_KIT_GENERATED_DIR,
  "ProductEvent.swift",
);

export const PRODUCT_EVENT_COVERAGE_SWIFT_PATH = join(
  COMPASS_KIT_GENERATED_DIR,
  "ProductEventNativeCoverage.swift",
);

export const parseProductEventNames = (trackSource: string): string[] => {
  const typeStart = trackSource.indexOf("export type ProductEvent =");
  if (typeStart === -1) {
    throw new Error("ProductEvent union not found in track.ts");
  }
  const unionBodyStart = trackSource.indexOf("|", typeStart);
  const unionBodyEnd = trackSource.indexOf(
    "export type ProductEventProperties",
  );
  if (unionBodyStart === -1 || unionBodyEnd === -1) {
    throw new Error("ProductEvent union boundaries not found in track.ts");
  }
  const unionBody = trackSource.slice(unionBodyStart, unionBodyEnd);
  const events = [...unionBody.matchAll(/\|\s*"([^"]+)"/g)].map(
    (match) => match[1] as string,
  );
  if (events.length === 0) {
    throw new Error("ProductEvent union parsed zero events");
  }
  return events;
};

export const emitProductEventSwift = (
  trackSource = readFileSync(TRACK_TS_PATH, "utf8"),
): string => {
  const events = parseProductEventNames(trackSource);
  const cases = events
    .map((event) => {
      const swiftCase = swiftEnumCaseName(snakeToCamelCase(event));
      return `    case ${swiftCase} = "${event}"`;
    })
    .join("\n");

  return `// Generated by bun cli desktop:export. Do not edit.

import Foundation

public enum ProductEvent: String, Codable, Hashable, Sendable, CaseIterable {
${cases}
}
`;
};

export const emitProductEventNativeCoverageSwift = (
  trackSource = readFileSync(TRACK_TS_PATH, "utf8"),
): string => {
  const allEvents = parseProductEventNames(trackSource);
  const nativeEvents = [...NATIVE_PRODUCT_EVENT_CALL_SITES];
  const nativeSet = new Set<string>(nativeEvents);
  for (const event of nativeEvents) {
    if (!allEvents.includes(event)) {
      throw new Error(
        `Native product event "${event}" is missing from track.ts`,
      );
    }
  }
  const webOnly = allEvents.filter((event) => !nativeSet.has(event));
  if (nativeEvents.length + webOnly.length !== allEvents.length) {
    throw new Error(
      "Native and web-only product events must partition track.ts",
    );
  }

  const swiftCase = (event: string) =>
    swiftEnumCaseName(snakeToCamelCase(event));
  const nativeCases = nativeEvents
    .map((event) => `        .${swiftCase(event)}`)
    .join(",\n");
  const webOnlyCases = webOnly
    .map((event) => `        .${swiftCase(event)}`)
    .join(",\n");

  return `// Generated by bun cli desktop:export. Do not edit.

import Foundation

public enum ProductEventNativeCoverage: Sendable {
    /// Events emitted from the native macOS app (see native-product-events.manifest.ts).
    public static let nativeCallSites: Set<ProductEvent> = [
${nativeCases}
    ]

    /// Events owned by the web client until a native call site is registered.
    public static let webOnly: Set<ProductEvent> = [
${webOnlyCases}
    ]

    public static func validatePartition() {
        let union = nativeCallSites.union(webOnly)
        precondition(union.count == ProductEvent.allCases.count)
        precondition(nativeCallSites.isDisjoint(with: webOnly))
    }
}
`;
};
