import {
  type ParsedThemeCss,
  parseThemeCss,
  SEMANTIC_THEME_TOKENS,
} from "@scripts/desktop-export/parse-theme-css";
import { COMPASS_KIT_GENERATED_DIR } from "@scripts/desktop-export/paths";
import {
  formatSwiftDouble,
  kebabToCamelCase,
} from "@scripts/desktop-export/swift-identifiers";
import { join } from "node:path";

export const THEME_TOKENS_SWIFT_PATH = join(
  COMPASS_KIT_GENERATED_DIR,
  "ThemeTokens.swift",
);

const swiftPropertyName = (token: string) => kebabToCamelCase(token);

const emitPaletteStruct = (name: string) =>
  `
public struct ${name}: Sendable, Equatable {
${SEMANTIC_THEME_TOKENS.map((token) => {
  const property = swiftPropertyName(token);
  return `    public let ${property}: ThemeTokenColor`;
}).join("\n")}

    public init(
${SEMANTIC_THEME_TOKENS.map((token) => {
  const property = swiftPropertyName(token);
  return `        ${property}: ThemeTokenColor`;
}).join(",\n")}
    ) {
${SEMANTIC_THEME_TOKENS.map((token) => {
  const property = swiftPropertyName(token);
  return `        self.${property} = ${property}`;
}).join("\n")}
    }
}`.trim();

const emitPaletteValue = (
  structName: string,
  paletteKey: keyof ParsedThemeCss,
  parsed: ParsedThemeCss,
) => {
  const args = SEMANTIC_THEME_TOKENS.map((token) => {
    const color = parsed[paletteKey][token];
    const property = swiftPropertyName(token);
    return `        ${property}: ThemeTokenColor(red: ${formatSwiftDouble(color.red)}, green: ${formatSwiftDouble(color.green)}, blue: ${formatSwiftDouble(color.blue)}, alpha: ${formatSwiftDouble(color.alpha)})`;
  }).join(",\n");
  return `    public static let ${paletteKey === "light-beach" ? "lightBeach" : "darkAbyss"} = ${structName}(\n${args}\n    )`;
};

export const emitThemeTokensSwift = (css: string): string => {
  const parsed = parseThemeCss(css);
  return `// Generated by bun cli desktop:export. Do not edit.

import Foundation

public struct ThemeTokenColor: Sendable, Equatable {
    public let red: Double
    public let green: Double
    public let blue: Double
    public let alpha: Double

    public init(red: Double, green: Double, blue: Double, alpha: Double) {
        self.red = red
        self.green = green
        self.blue = blue
        self.alpha = alpha
    }
}

${emitPaletteStruct("LightBeachPalette")}

${emitPaletteStruct("DarkAbyssPalette")}

public enum ThemeTokens {
${emitPaletteValue("LightBeachPalette", "light-beach", parsed)}
${emitPaletteValue("DarkAbyssPalette", "dark-abyss", parsed)}
}
`;
};
