import {
  COMPASS_KIT_GENERATED_DIR,
  COMPASS_KIT_RESOURCES_DIR,
} from "@scripts/desktop-export/paths";
import { swiftEnumCaseName } from "@scripts/desktop-export/swift-identifiers";
import { REGISTRY_RUNTIME_KEY_SOURCES } from "@core/shortcuts/app-shortcut-bindings";
import { EDIT_SEQUENCE_FIELDS } from "@core/shortcuts/edit-sequence.fields";
import { KEYMAP } from "@core/shortcuts/keymap";
import { SHORTCUT_LEVELS } from "@core/shortcuts/shortcut-level";
import { SHORTCUTS_REGISTRY } from "@core/shortcuts/shortcuts.registry";
import { join } from "node:path";

export interface ShortcutsExportDocument {
  registry: Array<{
    id: string;
    keys: string[];
    label: string;
    section: string;
    when?: Record<string, boolean>;
    requiresWrite?: boolean;
  }>;
  bindings: Record<string, readonly string[]>;
  keymap: typeof KEYMAP;
  editSequenceLeader: string;
  editSequenceFields: typeof EDIT_SEQUENCE_FIELDS;
  shortcutLevels: typeof SHORTCUT_LEVELS;
}

export const buildShortcutsExportDocument = (): ShortcutsExportDocument => ({
  registry: SHORTCUTS_REGISTRY.map((entry) => {
    const row: ShortcutsExportDocument["registry"][number] = {
      id: entry.id,
      keys: [...entry.keys],
      label: entry.label,
      section: entry.section,
    };
    if ("when" in entry && entry.when) {
      row.when = { ...entry.when };
    }
    if ("requiresWrite" in entry && entry.requiresWrite) {
      row.requiresWrite = true;
    }
    return row;
  }),
  bindings: Object.fromEntries(
    Object.entries(REGISTRY_RUNTIME_KEY_SOURCES).map(([id, keycaps]) => [
      id,
      [...keycaps],
    ]),
  ),
  keymap: KEYMAP,
  editSequenceLeader: KEYMAP.editTitle.sequence.leader,
  editSequenceFields: EDIT_SEQUENCE_FIELDS,
  shortcutLevels: SHORTCUT_LEVELS,
});

export const emitShortcutsJson = (): string =>
  `${JSON.stringify(buildShortcutsExportDocument(), null, 2)}\n`;

export const emitShortcutIdsSwift = (): string => {
  const cases = SHORTCUTS_REGISTRY.map(({ id }) => {
    const caseName = swiftEnumCaseName(id);
    return `    case ${caseName} = "${id}"`;
  }).join("\n");

  return `// Generated by bun cli desktop:export. Do not edit.

import Foundation

public enum ShortcutId: String, Codable, Hashable, Sendable, CaseIterable {
${cases}
}
`;
};

export const shortcutsExportPaths = {
  json: join(COMPASS_KIT_RESOURCES_DIR, "shortcuts.json"),
  swift: join(COMPASS_KIT_GENERATED_DIR, "ShortcutIds.swift"),
};
