import {
  emitContractsSwiftFile,
  emitSwiftForSchema,
  SwiftEmitError,
} from "@scripts/swift-contracts/emit-swift";
import { z } from "zod/v4";
import { describe, expect, it } from "bun:test";

describe("swift contract emitter", () => {
  it("emits string enums as CaseIterable Swift enums", () => {
    const schema = z.enum(["alpha", "beta"]);
    const swift = emitSwiftForSchema(schema, "Sample");
    expect(swift).toContain("public enum SampleEnum: String");
    expect(swift).toContain('case alpha = "alpha"');
    expect(swift).toContain("CaseIterable");
  });

  it("emits objects as Codable structs with optional fields", () => {
    const schema = z.object({
      name: z.string(),
      note: z.string().optional(),
    });
    const swift = emitSwiftForSchema(schema, "Sample");
    expect(swift).toContain(
      "public struct Sample: Codable, Hashable, Sendable",
    );
    expect(swift).toContain("name: String");
    expect(swift).toContain("note: String?");
  });

  it("reuses deduped payload structs across discriminated unions", () => {
    const singleVariant = z.object({ kind: z.literal("single") });
    const seriesVariant = z.object({
      kind: z.literal("series"),
      rrule: z.array(z.string()),
    });
    const preserveVariant = z.object({ kind: z.literal("preserve") });
    const first = z.discriminatedUnion("kind", [singleVariant, seriesVariant]);
    const second = z.discriminatedUnion("kind", [
      preserveVariant,
      singleVariant,
      seriesVariant,
    ]);
    const schema = z.object({ first, second });
    const swift = emitSwiftForSchema(schema, "Sample");
    expect(swift).toContain("case single(SampleFirst_SinglePayload)");
    expect(swift).toContain("case single(SampleFirst_SinglePayload)");
    expect(swift).not.toMatch(/SampleSecond_SinglePayload: Codable/);
    expect(swift).toContain(
      "self = .single(try SampleFirst_SinglePayload(from: decoder))",
    );
  });

  it("emits discriminated unions with custom init(from:)", () => {
    const schema = z.discriminatedUnion("kind", [
      z.object({ kind: z.literal("a"), value: z.number() }),
      z.object({ kind: z.literal("b"), label: z.string() }),
    ]);
    const swift = emitSwiftForSchema(schema, "Tagged");
    expect(swift).toContain("public enum Tagged: Codable, Hashable, Sendable");
    expect(swift).toContain("init(from decoder: Decoder)");
    expect(swift).toContain('case "a"');
  });

  it("maps branded ids via the name table", () => {
    const branded = z.string().min(1).max(256).brand<"EventId">();
    const swift = emitSwiftForSchema(z.object({ id: branded }), "Sample");
    expect(swift).toContain("id: EventId");
  });

  it("emits records as String-keyed dictionaries", () => {
    const schema = z.object({
      metadata: z.record(z.string(), z.unknown()),
    });
    const swift = emitSwiftForSchema(schema, "Sample");
    expect(swift).toContain("metadata: [String: JSONValue]");
  });

  it("fails on unsupported constructs with the schema path", () => {
    expect(() =>
      emitSwiftForSchema(z.union([z.number(), z.boolean()]), "Bad"),
    ).toThrow(SwiftEmitError);
  });

  it("generates a non-empty Contracts.swift bundle", () => {
    const output = emitContractsSwiftFile();
    expect(output).toContain(
      "// Generated by bun cli contracts:swift. Do not edit.",
    );
    expect(output).toContain("public struct Event: Codable");
    expect(output).toContain("public struct CompassCalendar: Codable");
    expect(output).toContain("public enum ServerMessage: Codable");
    expect(output).not.toContain("public struct Calendar: Codable");
    expect(output).not.toContain("public struct TimeZone: RawRepresentable");
  });
});
