import {
  emitContractsSwiftFile,
  emitSwiftForSchema,
  SwiftEmitError,
} from "@scripts/swift-contracts/emit-swift";
import { z } from "zod/v4";
import { describe, expect, it } from "bun:test";

describe("swift contract emitter", () => {
  it("emits string enums as CaseIterable Swift enums", () => {
    const schema = z.enum(["alpha", "beta"]);
    const swift = emitSwiftForSchema(schema, "Sample");
    expect(swift).toContain("public enum SampleEnum: String");
    expect(swift).toContain('case alpha = "alpha"');
    expect(swift).toContain("CaseIterable");
  });

  it("emits objects as Codable structs with optional fields", () => {
    const schema = z.object({
      name: z.string(),
      note: z.string().optional(),
    });
    const swift = emitSwiftForSchema(schema, "Sample");
    expect(swift).toContain(
      "public struct Sample: Codable, Hashable, Sendable",
    );
    expect(swift).toContain("name: String");
    expect(swift).toContain("note: String?");
  });

  it("emits discriminated unions with custom init(from:)", () => {
    const schema = z.discriminatedUnion("kind", [
      z.object({ kind: z.literal("a"), value: z.number() }),
      z.object({ kind: z.literal("b"), label: z.string() }),
    ]);
    const swift = emitSwiftForSchema(schema, "Tagged");
    expect(swift).toContain("public enum Tagged: Codable, Hashable, Sendable");
    expect(swift).toContain("init(from decoder: Decoder)");
    expect(swift).toContain('case "a"');
  });

  it("maps branded ids via the name table", () => {
    const branded = z.string().min(1).max(256).brand<"EventId">();
    const swift = emitSwiftForSchema(z.object({ id: branded }), "Sample");
    expect(swift).toContain("id: EventId");
  });

  it("emits records as String-keyed dictionaries", () => {
    const schema = z.object({
      metadata: z.record(z.string(), z.unknown()),
    });
    const swift = emitSwiftForSchema(schema, "Sample");
    expect(swift).toContain("metadata: [String: JSONValue]");
  });

  it("fails on unsupported constructs with the schema path", () => {
    expect(() =>
      emitSwiftForSchema(z.union([z.number(), z.boolean()]), "Bad"),
    ).toThrow(SwiftEmitError);
  });

  it("generates a non-empty Contracts.swift bundle", () => {
    const output = emitContractsSwiftFile();
    expect(output).toContain(
      "// Generated by bun cli contracts:swift. Do not edit.",
    );
    expect(output).toContain("public struct Event: Codable");
    expect(output).toContain("public enum ServerMessage: Codable");
  });
});
